services:
  mysql:
    image: mysql:8.0
    container_name: university_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3303:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
